=== Boole215/stretch-rx/.astro/collections/stretches.schema.json
{
  "$ref": "#/definitions/stretches",
  "definitions": {
    "stretches": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "preparation": {
          "type": "string"
        },
        "execution": {
          "type": "string"
        },
        "comments": {
          "type": "string"
        },
        "example": {
          "type": "string"
        },
        "exampleAlt": {
          "type": "string"
        },
        "targets": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "preparation",
        "execution",
        "example",
        "exampleAlt",
        "targets"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Boole215/stretch-rx/src/data/stretches/knee-to-chest.json
{
    "title" : "Knee-to-chest",
    "preparation": "Lie on your back on a comfortable surface with your knees bent and feet flat on the floor.",
    "execution": "Gently bring one knee up toward your chest, using both hands to pull it in closer. Keep the other foot flat on the floor. Hold the position for 15-30 seconds, feeling the stretch in your lower back and glutes. Slowly release the first leg and repeat with the other leg.",
    "example": "../../assets/knee-to-chest.gif",
    "exampleAlt": "Gif of woman doing knee-to-chest movement",
    "targets": ["hip-flexors", "glutes", "back", "hamstrings", "lower-back", "legs"]
}

=== Boole215/stretch-rx/src/data/stretches/fish-pose.json
{
    "title": "Fish Pose",
    "preparation":"Lie on your back on the floor with your legs extended. Tuck your forearms and elbows up close to the sides of your torso with palms facing up.",
    "execution": "Inhale and press your forearms and elbows firmly against the floor. Press your shoulder blades into your back and, with an inhale, lift your upper torso and head away from the floor.  Exhale while lowering your body back onto the floor.  Hold for 15 to 30 seconds, breathing smoothly.",
    "comments":"Depending on how high you arch your back and lift your chest, either the back or top of your head will rest on the floor. There should be a minimal amount of weight on your head to avoid straining your neck.",
    "example": "../../assets/fish-pose.gif",
    "exampleAlt": "Gif of man doing fish pose",
    "targets": ["chest"]
}

=== Boole215/stretch-rx/src/data/stretches/wall-crawl.json
{
    "title": "Wall Crawl",
    "preparation":"Stand up straight facing a wall. Extend your right arm with your elbow soft (not locked) and place your hand on the wall at shoulder height.",
    "execution": "Slowly walk your fingers upward, stepping in toward the wall as your hand climbs higher. Stop when you feel mild tension in your shoulder. Hold 10 to 30 seconds. Slowly walk your fingers back down the wall and return to the starting position. Repeat three to four times. Switch arms and repeat.",
    "example": "../../assets/wall-crawl.gif",
    "exampleAlt": "Gif of woman doing a wall crawl",
    "targets": ["shoulder"]
}

=== Boole215/stretch-rx/src/data/stretches/overhead-triceps-stretch.json
{
    "title": "Overhead Triceps Stretch",
    "preparation":"Put one arm overhead. Position forearm as close as possible to upper arm. Grasp elbow overhead with other hand.",
    "execution": "Pull elbow back and toward head. Hold stretch. Repeat with opposite arm.",
    "example": "../../assets/overhead-triceps-stretch.gif",
    "exampleAlt": "Gif of man doing overhead triceps stretch",
    "targets": ["arms"]
}

=== Boole215/stretch-rx/src/data/stretches/cat-cow.json
{
    "title" : "Cat-Cow",
    "preparation": "Kneel on the floor and put your hands on the floor in front of you. Keep your hands shoulder-width apart and your knees directly below your hips.",
    "execution": "Inhale deeply while curving your lower back and bringing your head up, tilting your pelvis up like a \"cow.\" Exhale deeply and bring your abdomen in, arching your spine and bringing your head and pelvis down like a \"cat.\" Repeat several times.",
    "example": "../../assets/cat-cow.gif",
    "exampleAlt": "Gif of woman doing cat-cow movement",
    "targets": ["upper-back", "lower-back", "back"]
}
